name: Pre-commit Run
description: Runs pre-commit to validate code and check user didn't bypass pre-commit hooks
inputs:
  terraform_version:
    description: 'Terraform Version'
    default: '1.4.2'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install Pre-Commit
      id: install-pre-commit
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pip install black

    - name: Install utilities
      id: install-utils
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

# Terraform docs excluded as it is hard to understand pre-commit failure in docs hook and address the issue from local machine
#        curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.18.0/terraform-docs-v0.18.0-$(uname)-amd64.tar.gz
#        tar -xzf terraform-docs.tar.gz
#        chmod +x terraform-docs
#        mv terraform-docs /usr/local/bin/terraform-docs

    - name: "setup-terraform"
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Pre-commit Install
      id: pre-commit-install
      shell: bash
      run: pre-commit install

    - name: Pre-commit run
      id: pre-commit-run
      shell: bash
      run: |
        git fetch origin main
        SKIP=terraform_docs pre-commit run --from-ref origin/main --to-ref HEAD
        EXIT_CODE=$?
        if [ $EXIT_CODE -ne 0 ]; then
          echo "Pre-commit detected issues or changes."
          exit 1
        fi
        echo "Pre-commit passed with no issues."