name: "Destroy TF resources"

on:
  workflow_dispatch:
    inputs:
      target_dir:
        required: true
        description: 'Target to destroy'
        type: string
      #branch of target
env:
  TF_VERSION: 1.6.6
  AWS_GH_ROLE: ${{secrets.AWS_GH_ROLE}}
  TF_BUCKET: vuln-alert-response-lambda-bjo-state-bucket
  TF_DYNAMO_DB: vuln-alert-response-lambda-bjo-state-table
permissions:
  id-token: write
  contents: read
  pull-requests: read
  checks: write

jobs:
  terraform_destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    #TODO
    outputs:
      terraform_plan_exitcode: ${{ steps.tf_destroy.outputs.terraform_plan_exitcode }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: AWS login
        id: aws_login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          role-to-assume: ${{ env.AWS_GH_ROLE }}
          role-duration-seconds: 900
          role-session-name: tfghIACSession

      - name: Terraform Plan
        id: tf_destroy
        uses: ./.github/actions/tf_run
        with:
          terraform_action: 'destroy'
          terraform_version: ${{ env.TF_VERSION }}
          tfstate_bucket: ${{ env.TF_BUCKET }}
          tfstate_dynamodb_table: ${{ env.TF_DYNAMO_DB }}
          tf_working_dir: ${{ inputs.target_dir}}
  